version: '3.8'

services: 
  postgres:
    image: postgres:10.4
    ports: 
      - '5428:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: